apiVersion: v1
kind: Secret
metadata:
  name: project-cobra-secrets
  namespace: project-cobra
type: Opaque
data:
  JWT_SECRET: ${JWT_SECRET}
  STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
