export enum DisputeStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  BUREAU_REVIEWING = 'BUREAU_REVIEWING',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED'
}
